services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
      - storage_data:/usr/src/app/storage
    ports:
      - "3000:3000" # Cambiado al puerto 3000
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password
    tty: true
    stdin_open: true

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: laboratorio_unas_development
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432" # Mantén el puerto 5433 para evitar conflictos con PostgreSQL local

volumes:
  pgdata:
  storage_data: