default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: password
  host: db
  port: 5432

development:
  <<: *default
  database: laboratorio_unas_development

test:
  <<: *default
  database: laboratorio_unas_test

production:
  <<: *default
  database: laboratorio_unas_production